### ISSUE TITLE
Modularize Documentation

### ISSUE THREAD

**Issue by cuioss** [cuioss/cui-java-tools#4]
## Summary

Currently the documentation is big document: README.adoc
This needs to modularized.

## Tasks

- Split up into sensible blocks 
- Move all elements to src/site/adoc. Include into site-map
- Configure the site plugin in order to deploy the pages correctly
- Include / reference file in README.adoc: Info: adoc include does not work within gitHub, therefore it is about linking
- Sync it with the corresponding package-javadoc files. Currently the README.adoc is more complete

**Comment by DLSV** [comment]
Hello,

I'd like to help out with this issue. Let me know if there's anything else to take into account.

**Comment by cuioss** [comment]
Hi DLSV
Welcome to our CUIOSS project(s)
Thanks for the offer, this is very much appreciated. 
You are welcome to this issue. 
Regards
Oliver
