### ISSUE TITLE
SecuritySupportWithSecurityManagerTest fails with Java 19

### ISSUE THREAD

**Issue by EugenFischer** [cuioss/cui-java-tools#7]
On execute SecuritySupportWithSecurityManagerTest with Java 19, all tests of the class are failing with UnsupportedOperationException

**Comment by cuioss** [comment]
Security-Manager is deprecated, starting with jdk 17, see https://openjdk.org/jeps/411 for details. Therefore, we will remove it

**Comment by cuioss** [comment]
Fixed, Matrix build now with 17 & 20
